/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import util.DBConnection;

/**
 *
 * @author Gayan
 */
public class ReportDAO {
    
    // Method to get total revenue generated by each dentist (Value-added Report)
    public List<String> getRevenueByDentist() {
        
        List<String> reportData = new ArrayList<>();
        Connection conn = DBConnection.getInstance().getConnection();
        
        try {
            // SQL query using JOIN and GROUP BY to calculate revenue per dentist
            String sql = "SELECT d.name, SUM(b.total_cost) as total_revenue " +
                         "FROM bill b " +
                         "JOIN appointment a ON b.appointment_no = a.appointment_no " +
                         "JOIN dentist d ON a.dentist_id = d.dentist_id " +
                         "GROUP BY d.dentist_id";
                         
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            // Loop through the results and add to the list
            while (rs.next()) {
                String record = "Dentist: " + rs.getString("name") + " | Total Revenue: Rs. " + rs.getDouble("total_revenue");
                reportData.add(record);
            }
            
        } catch (Exception e) {
            System.out.println("Error generating report in ReportDAO: " + e.getMessage());
        }
        
        return reportData;
    }
}