/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Gayan
 */
public class MainDashboardUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboardUI.class.getName());

    /**
     * Creates new form MainDashboardUI
     */
    public MainDashboardUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnAppointments = new javax.swing.JButton();
        btnPatientHistory = new javax.swing.JButton();
        btnDentistMgmt = new javax.swing.JButton();
        btnManageBill = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToggleButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\sunrise new logo100px.jpg")); // NOI18N
        jToggleButton1.setText("jToggleButton1");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Sunrise Dental Clinic - Main Dashboard");

        btnAppointments.setBackground(new java.awt.Color(0, 153, 153));
        btnAppointments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAppointments.setForeground(new java.awt.Color(255, 255, 255));
        btnAppointments.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\appointment30.png")); // NOI18N
        btnAppointments.setText("1. Manage Appiontment");
        btnAppointments.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAppointments.addActionListener(this::btnAppointmentsActionPerformed);

        btnPatientHistory.setBackground(new java.awt.Color(153, 153, 153));
        btnPatientHistory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPatientHistory.setForeground(new java.awt.Color(51, 51, 51));
        btnPatientHistory.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\history30.png")); // NOI18N
        btnPatientHistory.setText("2. Patient History Tracking ");
        btnPatientHistory.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPatientHistory.addActionListener(this::btnPatientHistoryActionPerformed);

        btnDentistMgmt.setBackground(new java.awt.Color(0, 153, 153));
        btnDentistMgmt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDentistMgmt.setForeground(new java.awt.Color(255, 255, 255));
        btnDentistMgmt.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\doc30.png")); // NOI18N
        btnDentistMgmt.setText("3. Dentiest Management");
        btnDentistMgmt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDentistMgmt.addActionListener(this::btnDentistMgmtActionPerformed);

        btnManageBill.setBackground(new java.awt.Color(153, 153, 153));
        btnManageBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageBill.setForeground(new java.awt.Color(51, 51, 51));
        btnManageBill.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\bill.png")); // NOI18N
        btnManageBill.setText("4. Billing System ");
        btnManageBill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnManageBill.addActionListener(this::btnManageBillActionPerformed);

        btnReports.setBackground(new java.awt.Color(0, 153, 153));
        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\report30.png")); // NOI18N
        btnReports.setText("5. Mangement Report ");
        btnReports.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnHelp.setBackground(new java.awt.Color(153, 153, 153));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(51, 51, 51));
        btnHelp.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\help30.png")); // NOI18N
        btnHelp.setText("6. Help Section");
        btnHelp.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHelp.addActionListener(this::btnHelpActionPerformed);

        btnLogout.setBackground(new java.awt.Color(0, 153, 153));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\logout30.png")); // NOI18N
        btnLogout.setText("7. Logout");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(51, 51, 51));
        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\exit30.png")); // NOI18N
        btnExit.setText("8. Exit System");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExit.addActionListener(this::btnExitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                            .addComponent(btnDentistMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPatientHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDentistMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageBill, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        // TODO add your handling code here:
        new ManageAppointmentsUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnDentistMgmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDentistMgmtActionPerformed
        // TODO add your handling code here:
        new ManageDentistsUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDentistMgmtActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        new ReportsUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        // TODO add your handling code here:
        new PatientHistoryUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnManageBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBillActionPerformed
        // TODO add your handling code here:
        new ManageBillUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageBillActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        
        displayHelpInformation();
     
    }//GEN-LAST:event_btnHelpActionPerformed

    
    private void displayHelpInformation() {
        String helpText = "Sunrise Dental Clinic - System Guide\n\n"
        + "1. Manage Appointments: Add, Update, or Search patient appointments.\n"
        + "2. Billing: Enter Appointment No to calculate total fees and print bills.\n"
        + "3. Reports: View financial reports securely.\n\n"
        + "Contact the System Administrator for technical support.";
        
        javax.swing.JOptionPane.showMessageDialog(this, helpText, "Help & Instructions", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new controller.AuthenticationService().logout(); 
        new LoginUI().setVisible(true); // LoginUI
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to exit the system?", "Exit Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0); 
}
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboardUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnDentistMgmt;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageBill;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
