/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Gayan
 */
public class ManageAppointmentsUI extends javax.swing.JFrame {
    
    private controller.AppointmentController apptController;
    private javax.swing.table.DefaultTableModel tableModel;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAppointmentsUI.class.getName());

    /**
     * Creates new form ManageAppointmentsUI
     */
    public ManageAppointmentsUI() {
        initComponents();
        
        apptController = new controller.AppointmentController();
        setLocationRelativeTo(null); // Center the window

    // Setup Table Columns manually to match your logic
    String[] columns = {"Appt No", "Patient ID", "Patient Name", "Dentist ID", "Date", "Time"};
    tableModel = new javax.swing.table.DefaultTableModel(columns, 0);
    tableAppointments.setModel(tableModel);

    // Load Initial Data
    loadTableData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAppointments = new javax.swing.JTable();
        btnAddNew = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\search-20.png")); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tableAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appt No", "Patient ID", "Patient Name", "Dentist ID", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(tableAppointments);

        btnAddNew.setBackground(new java.awt.Color(0, 153, 102));
        btnAddNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddNew.setForeground(new java.awt.Color(51, 51, 51));
        btnAddNew.setText("Add New Appoinment");
        btnAddNew.addActionListener(this::btnAddNewActionPerformed);

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Updete /Edit Appoinment");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Cancel Appoinment");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Main Menu");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Search (Patient ID or Name)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnAddNew)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnBack))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tableAppointments.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment from the table to delete!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

            String apptNo = tableModel.getValueAt(selectedRow, 0).toString();

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                    "Are you sure you want to cancel Appointment No: " + apptNo + "?", 
                    "Confirm Deletion", 
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                boolean isDeleted = apptController.deleteAppointment(apptNo);

                if (isDeleted) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Appointment cancelled successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    loadTableData(""); 
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to cancel appointment. It might have existing bills.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        new MainDashboardUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        String keyword = txtSearch.getText().trim();
        loadTableData(keyword); // search button
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        
        new RegisterAppointmentUI().setVisible(true);
        this.dispose(); // regester new appoinment
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
            int selectedRow = tableAppointments.getSelectedRow();

            if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment from the table to update!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String apptNo = tableModel.getValueAt(selectedRow, 0).toString();
        String currentDate = tableModel.getValueAt(selectedRow, 4).toString();
        String currentTime = tableModel.getValueAt(selectedRow, 5).toString();

        javax.swing.JTextField txtNewDate = new javax.swing.JTextField(currentDate);
        javax.swing.JTextField txtNewTime = new javax.swing.JTextField(currentTime);

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(2, 2, 10, 10));
        panel.add(new javax.swing.JLabel("New Date (YYYY-MM-DD):"));
        panel.add(txtNewDate);
        panel.add(new javax.swing.JLabel("New Time (HH:MM:SS):"));
        panel.add(txtNewTime);

        int result = javax.swing.JOptionPane.showConfirmDialog(this, panel, "Update Appointment: " + apptNo, javax.swing.JOptionPane.OK_CANCEL_OPTION, javax.swing.JOptionPane.PLAIN_MESSAGE);

            if (result == javax.swing.JOptionPane.OK_OPTION) {
            String newDate = txtNewDate.getText().trim();
            String newTime = txtNewTime.getText().trim();

        boolean isUpdated = apptController.updateAppointment(apptNo, newDate, newTime);

            if (isUpdated) {
             javax.swing.JOptionPane.showMessageDialog(this, "Appointment updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                loadTableData(""); 
        }    else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to update appointment. Check date/time format.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
       }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageAppointmentsUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAppointments;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    
    private void loadTableData(String keyword) {
        tableModel.setRowCount(0); 
        java.util.List<Object[]> records = apptController.getAppointmentsList(keyword);
        
        for (Object[] row : records) {
            tableModel.addRow(row); // load to table
        }
    }

}

