/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;

/**
 *
 * @author Gayan
 */
public class ManageBillUI extends javax.swing.JFrame {
    
    private controller.BillController billController;
    private double currentConsultationFee = 0.0;
    private final double BOOKING_FEE = 100.0; 
    private double currentTreatmentFee = 0.0;
    private String currentTreatmentDesc = "";
    private double calculatedTotal = 0.0;
    private String selectedApptNo = "";
    private String selectedDoctorName = ""; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageBillUI.class.getName());

    /**
     * Creates new form ManageBillUI
     */
    public ManageBillUI() {
        initComponents();
        
        billController = new controller.BillController();
        setLocationRelativeTo(null); // Center the window
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBills = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTreatmentDesc = new javax.swing.JTextField();
        txtTreatmentFee = new javax.swing.JTextField();
        lblConsultationFee = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Search (Patient Name or Appoinment No");

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gayan\\Downloads\\icon foe sunrise\\search-20.png")); // NOI18N
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tableBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment No", "Patient Name", "Patient ID", "Doctor Name", "Doctor Fee (Rs)l"
            }
        ));
        tableBills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBillsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBills);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Treatment Details (Optional) ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Treament Fee (Rs)");

        lblConsultationFee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConsultationFee.setText("Consultation Fee: Rs. 0.00");

        lblTotalCost.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalCost.setForeground(new java.awt.Color(0, 102, 102));
        lblTotalCost.setText("Total Cost: Rs. 0.00");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Booking Fee: Rs. 100.00");

        btnGenerate.setBackground(new java.awt.Color(0, 153, 51));
        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setText("Generate Bill");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);

        btnPrint.setBackground(new java.awt.Color(153, 0, 0));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print Bil");
        btnPrint.setEnabled(false);
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        btnBack.setBackground(new java.awt.Color(0, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back to Dashboard");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTreatmentDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                        .addComponent(txtTreatmentFee)))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTreatmentDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultationFee)
                    .addComponent(jLabel4))
                .addGap(57, 57, 57)
                .addComponent(lblTotalCost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnPrint)
                    .addComponent(btnBack))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBillsMouseClicked

        // Get the selected row number
        int row = tableBills.getSelectedRow();
        
        if (row != -1) {
            selectedApptNo = tableBills.getModel().getValueAt(row, 0).toString();
            
            // NEW: Get the Doctor's name from column 3 (Index 3)
            selectedDoctorName = tableBills.getModel().getValueAt(row, 3).toString(); 
            
            currentConsultationFee = Double.parseDouble(tableBills.getModel().getValueAt(row, 4).toString());
            lblConsultationFee.setText("Consultation Fee: Rs. " + currentConsultationFee);
            lblTotalCost.setText("Total Cost: Rs. 0.00"); 
            btnPrint.setEnabled(false);
        
       
     }
    }//GEN-LAST:event_tableBillsMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        String keyword = txtSearch.getText().trim();
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tableBills.getModel();
    model.setRowCount(0); 

    java.util.List<Object[]> records = billController.searchBillDetails(keyword);
    for (Object[] row : records) {
        model.addRow(row);
    }

    // Reset fields
    lblConsultationFee.setText("Consultation Fee: Rs. 0.00");
    lblTotalCost.setText("Total Cost: Rs. 0.00");
    txtTreatmentDesc.setText("");
    txtTreatmentFee.setText("");
    btnPrint.setEnabled(false);
    selectedApptNo = "";
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        
        if (selectedApptNo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment from the table first!", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    currentTreatmentFee = 0.0;
    currentTreatmentDesc = txtTreatmentDesc.getText().trim();
    String feeText = txtTreatmentFee.getText().trim();

    if (!feeText.isEmpty()) {
        try {
            currentTreatmentFee = Double.parseDouble(feeText);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for the Treatment Fee!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    calculatedTotal = currentConsultationFee + BOOKING_FEE + currentTreatmentFee;
    lblTotalCost.setText("Total Cost: Rs. " + calculatedTotal);
    btnPrint.setEnabled(true); 
    javax.swing.JOptionPane.showMessageDialog(this, "Bill Generated Successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
       // Generate a random bill number
        String generatedBillNo = "B" + (int)(Math.random() * 10000);

        // 1. Save bill to the database first
        boolean isSaved = saveBill(generatedBillNo, selectedApptNo, calculatedTotal);

        if (isSaved) {
            String currentDate = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

            try {
                // 2. PDF save name and location eg B1234_Invoice.pdf
                String filePath = generatedBillNo + "_Invoice.pdf";
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(filePath));

                // open document and writing
                document.open();

                // 3. genarate fonts
                Font titleFont = new Font(Font.FontFamily.HELVETICA, 20, Font.BOLD);
                Font normalFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);
                Font boldFont = new Font(Font.FontFamily.HELVETICA, 13, Font.BOLD);

                // 4. PDF details
                Paragraph title = new Paragraph("SUNRISE DENTAL CLINIC", titleFont);
                title.setAlignment(Element.ALIGN_CENTER); // center
                document.add(title);
                
                Paragraph subTitle = new Paragraph("Official Payment Receipt\n\n", normalFont);
                subTitle.setAlignment(Element.ALIGN_CENTER);
                document.add(subTitle);

                document.add(new Paragraph("Date & Time : " + currentDate, normalFont));
                document.add(new Paragraph("Bill No     : " + generatedBillNo, normalFont));
                document.add(new Paragraph("Appt No     : " + selectedApptNo, normalFont));
                document.add(new Paragraph("Doctor Name : " + selectedDoctorName, normalFont));
                document.add(new Paragraph("-----------------------------------------------------------------------------------------", normalFont));

                document.add(new Paragraph("Consultation Fee : Rs. " + currentConsultationFee, normalFont));
                document.add(new Paragraph("Booking Fee      : Rs. " + BOOKING_FEE, normalFont));

                if (currentTreatmentFee > 0) {
                    String desc = currentTreatmentDesc.isEmpty() ? "Medical Treatment" : currentTreatmentDesc;
                    document.add(new Paragraph("Treatment (" + desc + ") : Rs. " + currentTreatmentFee, normalFont));
                }

                document.add(new Paragraph("-----------------------------------------------------------------------------------------", normalFont));
                
                Paragraph total = new Paragraph("TOTAL COST       : Rs. " + calculatedTotal, boldFont);
                document.add(total);
                document.add(new Paragraph("==========================================================", normalFont));
                
                Paragraph footer = new Paragraph("\nThank you! Wish you well!\n-- Hotline : 011 5347538 --", normalFont);
                footer.setAlignment(Element.ALIGN_CENTER);
                document.add(footer);

                // save as Document and close it
                document.close();

                // 5. display Success Message 
                javax.swing.JOptionPane.showMessageDialog(this, "Bill Saved & PDF Generated Successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                btnPrint.setEnabled(false); 

                // 6. PDF open popup (AUTO OPEN)
                File pdfFile = new File(filePath);
                if (pdfFile.exists()) {
                    if (Desktop.isDesktopSupported()) {
                        Desktop.getDesktop().open(pdfFile); // open as a pdf
                    } else {
                        System.out.println("Desktop is not supported. Cannot auto-open the PDF.");
                    }
                }

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error generating PDF: " + e.getMessage(), "PDF Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to save the bill to the Database! Check Database connection.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        new MainDashboardUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageBillUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultationFee;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JTable tableBills;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTreatmentDesc;
    private javax.swing.JTextField txtTreatmentFee;
    // End of variables declaration//GEN-END:variables

// Method to save the generated bill to the database
    public boolean saveBill(String billNo, String apptNo, double totalCost) {
        model.Bill b = new model.Bill();
        b.setBillNo(billNo);
        b.setAppointmentNo(apptNo);
        b.setTotalCost(totalCost);
        
        dao.BillDAO billDAO = new dao.BillDAO();
        return billDAO.insertBill(b);
    }

}
